### ISSUE TITLE
No module named 'fuzzywuzzy'

### ISSUE THREAD

**Issue by aweder** [yangzuoming/AutoXue-multiuser#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\AutoXue-multiuser\xuexi\__init__.py", line 28, in <module>
    from xuexi.model_local import TikuQuery
  File "D:\AutoXue-multiuser\xuexi\model_local.py", line 7, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'

**Comment by zz803abc** [comment]
我也是同样的错误

![image](https://user-images.githubusercontent.com/50546321/93441973-79fb8900-f902-11ea-988e-13a7cc2fb4d6.png)

**Comment by yangzuoming** [comment]
安装一下fuzzywuzzy，如果你用pycharm会提示你安装。

pip install git+git://github.com/seatgeek/fuzzywuzzy.git@0.17.0#egg=fuzzywuzzy

**Comment by zz803abc** [comment]
> 安装一下fuzzywuzzy，如果你用pycharm会提示你安装。
> pip install fuzzywuzzy
> 或者
> pip install git+git://github.com/seatgeek/fuzzywuzzy.git@0.17.0#egg=fuzzywuzzy

![image](https://user-images.githubusercontent.com/50546321/93552118-43754b00-f9a2-11ea-8829-4d0b55cb92b2.png)

已装好，还是不行，还是出上面的错误。

**Comment by XueBab** [comment]
同样的问题， fuzzywuzzy安装过了
![image](https://user-images.githubusercontent.com/57139408/93621168-c2539d80-fa0d-11ea-872e-43a9aff3bd65.png)

**Comment by XueBab** [comment]
修改了两个bat里面夜神模拟器的地址并且把nox_adb.exe命令改为adb connect ....这样前半部分可以正常运行，现在不提示找不到fuzzywuzzy了，提示需要lxml库，再运行需要bs4，然后出现“name 'app' is not defined”，希望作者有时间可以回复一下，感谢！

**Comment by XueBab** [comment]
解决了，在config里把安卓版本号和设备名称按照模拟器里的信息修改一下就可以了，现在正在测试答题中

**Comment by XueBab** [comment]
在main里修改自己账号后 到答题这一步出问题
![image](https://user-images.githubusercontent.com/57139408/93623443-55da9d80-fa11-11ea-882f-b201eb8d22dc.png)

**Comment by yangzuoming** [comment]
> 在main里修改自己账号后 到答题这一步出问题
> ![image](https://user-images.githubusercontent.com/57139408/93623443-55da9d80-fa11-11ea-882f-b201eb8d22dc.png)

不好意思，因为我的夜神模拟器不自动链接adb，我在批处理里加了adb链接，已经移除了，后续可以正常执行，不知道为什么你截图总是看不到，我今天继续测试一次看看问题出在哪里。

**Comment by yangzuoming** [comment]
> 在main里修改自己账号后 到答题这一步出问题

不好意思，因为我的夜神模拟器不自动链接adb，我在批处理里加了adb链接，已经移除了，后续可以正常执行，这个系统设置的是循环执行，我看你错误是没有读取到各个项目分数；建议运行程序的时候不要点击模拟器app，我电脑很卡顿，运行模拟器也有这个问题，多循环几次试试，如果还有问题截图给我。

**Comment by XueBab** [comment]
刚回到家测试运行了一下，无限登录注销登录，日志贴在下面
C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master>adb connect 127.0.0.1:62001
already connected to 127.0.0.1:62001
C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master
Appium.exe                    6464 Console                    1    134,736 K
Appium.exe                   10784 Console                    1     72,552 K
Appium.exe                   11108 Console                    1     21,244 K
Appium.exe                   10996 Console                    1    136,576 K
Nox.exe                       8756 Console                    1     27,820 K
C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master\venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
[INFO] app未登录
[INFO] 开始学习XXX39999102的账号
[INFO] 登录, (1, 1)
[INFO] 我要选读文章, (0, 12)
[INFO] 视听学习, (0, 6)
[INFO] 刷分出现如下异常    not enough values to unpack (expected 2, got 0)
[INFO] 退出APP出现如下异常    name 'app' is not defined
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
[INFO] 发现app已经登录，退出重新登录
[INFO] 已注销
[INFO] 开始学习XXX39999102的账号
[INFO] 登录, (1, 1)
[INFO] 我要选读文章, (0, 12)
[INFO] 视听学习, (0, 6)
[INFO] 刷分出现如下异常    not enough values to unpack (expected 2, got 0)
[INFO] 退出APP出现如下异常    name 'app' is not defined
[INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
[INFO] 模拟器 127.0.0.1:62001 连接成功
[INFO] 打开 appium 服务,正在配置...
在这里是无限循环的，不知道问题出在什么地方……

**Comment by yangzuoming** [comment]
> 刚回到家测试运行了一下，无限登录注销登录，日志贴在下面
> C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master>adb connect 127.0.0.1:62001
> already connected to 127.0.0.1:62001
> C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master
> Appium.exe 6464 Console 1 134,736 K
> Appium.exe 10784 Console 1 72,552 K
> Appium.exe 11108 Console 1 21,244 K
> Appium.exe 10996 Console 1 136,576 K
> Nox.exe 8756 Console 1 27,820 K
> C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master\venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
> warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
> [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> [INFO] 模拟器 127.0.0.1:62001 连接成功
> [INFO] 打开 appium 服务,正在配置...
> [INFO] app未登录
> [INFO] 开始学习XXX39999102的账号
> [INFO] 登录, (1, 1)
> [INFO] 我要选读文章, (0, 12)
> [INFO] 视听学习, (0, 6)
> [INFO] 刷分出现如下异常 not enough values to unpack (expected 2, got 0)
> [INFO] 退出APP出现如下异常 name 'app' is not defined
> [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> [INFO] 模拟器 127.0.0.1:62001 连接成功
> [INFO] 打开 appium 服务,正在配置...
> [INFO] 发现app已经登录，退出重新登录
> [INFO] 已注销
> [INFO] 开始学习XXX39999102的账号
> [INFO] 登录, (1, 1)
> [INFO] 我要选读文章, (0, 12)
> [INFO] 视听学习, (0, 6)
> [INFO] 刷分出现如下异常 not enough values to unpack (expected 2, got 0)
> [INFO] 退出APP出现如下异常 name 'app' is not defined
> [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> [INFO] 模拟器 127.0.0.1:62001 连接成功
> [INFO] 打开 appium 服务,正在配置...
> 在这里是无限循环的，不知道问题出在什么地方……

重新下载试试，这个问题我也出现过，你的夜神浏览器是不是也卡顿，反应慢，我增加了sleep 5秒，再测试一下。

**Comment by XueBab** [comment]
> > 刚回到家测试运行了一下，无限登录注销登录，日志贴在下面
> > C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master>adb connect 127.0.0.1:62001
> > already connected to 127.0.0.1:62001
> > C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master
> > Appium.exe 6464 Console 1 134,736 K
> > Appium.exe 10784 Console 1 72,552 K
> > Appium.exe 11108 Console 1 21,244 K
> > Appium.exe 10996 Console 1 136,576 K
> > Nox.exe 8756 Console 1 27,820 K
> > C:\Users\XueBab\Desktop\TechXueXi\AutoXue-multiuser-master\venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
> > warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
> > [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> > [INFO] 模拟器 127.0.0.1:62001 连接成功
> > [INFO] 打开 appium 服务,正在配置...
> > [INFO] app未登录
> > [INFO] 开始学习XXX39999102的账号
> > [INFO] 登录, (1, 1)
> > [INFO] 我要选读文章, (0, 12)
> > [INFO] 视听学习, (0, 6)
> > [INFO] 刷分出现如下异常 not enough values to unpack (expected 2, got 0)
> > [INFO] 退出APP出现如下异常 name 'app' is not defined
> > [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> > [INFO] 模拟器 127.0.0.1:62001 连接成功
> > [INFO] 打开 appium 服务,正在配置...
> > [INFO] 发现app已经登录，退出重新登录
> > [INFO] 已注销
> > [INFO] 开始学习XXX39999102的账号
> > [INFO] 登录, (1, 1)
> > [INFO] 我要选读文章, (0, 12)
> > [INFO] 视听学习, (0, 6)
> > [INFO] 刷分出现如下异常 not enough values to unpack (expected 2, got 0)
> > [INFO] 退出APP出现如下异常 name 'app' is not defined
> > [INFO] 正在连接模拟器 127.0.0.1:62001，请稍候...
> > [INFO] 模拟器 127.0.0.1:62001 连接成功
> > [INFO] 打开 appium 服务,正在配置...
> > 在这里是无限循环的，不知道问题出在什么地方……
> 
> 重新下载试试，这个问题我也出现过，你的夜神浏览器是不是也卡顿，反应慢，我增加了sleep 5秒，再测试一下。

重新下载的包运行start提示系统无法找到路径 我懵了

**Comment by XueBab** [comment]
C:\Users\XueBab\Desktop\TechXueXi\111
Appium.exe                   16856 Console                    1    149,688 K
Appium.exe                   15864 Console                    1     71,564 K
Appium.exe                   15736 Console                    1     21,464 K
Appium.exe                    9004 Console                    1    134,568 K
Nox.exe                      13664 Console                    1     30,852 K
C:\Users\XueBab\Desktop\TechXueXi\111\venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
请按任意键继续. . .

**Comment by yangzuoming** [comment]
> C:\Users\XueBab\Desktop\TechXueXi\111
> Appium.exe 16856 Console 1 149,688 K
> Appium.exe 15864 Console 1 71,564 K
> Appium.exe 15736 Console 1 21,464 K
> Appium.exe 9004 Console 1 134,568 K
> Nox.exe 13664 Console 1 30,852 K
> C:\Users\XueBab\Desktop\TechXueXi\111\venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
> warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
> 请按任意键继续. . .
main函数兄弟，增加你的账号

**Comment by XueBab** [comment]
if __name__ == "__main__":
    # xuexitiaozhan = Tiku()
    # xuexitiaozhan.get_tiku()
    user_list = [
        # ['XXX39999102', 'he6212960'],
    ]


是这个段落吗，添加之后还是一样的问题……

**Comment by yangzuoming** [comment]
> if **name** == "**main**":
> # xuexitiaozhan = Tiku()
> # xuexitiaozhan.get_tiku()
> user_list = [
> # ['XXX39999102', 'he6212960'],
> ]
> 
> 是这个段落吗，添加之后还是一样的问题……
对，请把#去掉，那是注释，修改为
 ['XXX39999102', 'he6212960'], 对齐

**Comment by XueBab** [comment]
[INFO] 刷分出现如下异常 not enough values to unpack (expected 2, got 0)
[INFO] 退出APP出现如下异常 name 'app' is not defined


还是卡在这个部分进行不下去了，我都不好意思问了  T^T

**Comment by yangzuoming** [comment]
你盯着app，看看读取我的分数那个页面什么状态，拍照发来看看。

**Comment by XueBab** [comment]
> 你盯着app，看看读取我的分数那个页面什么状态，拍照发来看看。

![image](https://user-images.githubusercontent.com/57139408/93669988-584cfe00-faca-11ea-8ef9-46b36595a017.png)

**Comment by XueBab** [comment]
> 你盯着app，看看读取我的分数那个页面什么状态，拍照发来看看。

![image](https://user-images.githubusercontent.com/57139408/93670039-b548b400-faca-11ea-9fc1-7967c0e3d984.png)

**Comment by yangzuoming** [comment]
之前版本有这个问题吗，我这里都能读出来全部状态，我再找找问题。

**Comment by XueBab** [comment]
> 之前版本有这个问题吗，我这里都能读出来全部状态，我再找找问题。

从昨天晚上到刚才更新的版本，都是在这一步出现问题的

**Comment by yangzuoming** [comment]
> > 之前版本有这个问题吗，我这里都能读出来全部状态，我再找找问题。
> 
> 从昨天晚上到刚才更新的版本，都是在这一步出现问题的

原作者的版本运行正常吗？

**Comment by yangzuoming** [comment]
> > 之前版本有这个问题吗，我这里都能读出来全部状态，我再找找问题。
> 
> 从昨天晚上到刚才更新的版本，都是在这一步出现问题的
我又更新了一稿，同步下来，修改配置文件用户名再试试。

**Comment by XueBab** [comment]
> > > 之前版本有这个问题吗，我这里都能读出来全部状态，我再找找问题。
> > 
> > 
> > 从昨天晚上到刚才更新的版本，都是在这一步出现问题的
> 
> 原作者的版本运行正常吗？

Traceback (most recent call last):
  File "H:\Tools\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\Tools\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XueBab\Desktop\Kessil\xuexi\__main__.py", line 17, in <module>
    app = App()
  File "C:\Users\XueBab\Desktop\Kessil\xuexi\__init__.py", line 121, in __init__
    self._challenge_init()
  File "C:\Users\XueBab\Desktop\Kessil\xuexi\__init__.py", line 206, in _challenge_init
    g, t = self.score["挑战答题"]
ValueError: not enough values to unpack (expected 2, got 0)
xuexi successfully!
请按任意键继续. . .

以前原作者版本运行正常，刚重装了系统 这是原作者版本的日志

**Comment by XueBab** [comment]
> > > 之前版本有这个问题吗，我这里都能读出来全部状态，我再找找问题。
> > 
> > 
> > 从昨天晚上到刚才更新的版本，都是在这一步出现问题的
> > 我又更新了一稿，同步下来，修改配置文件用户名再试试。

好的，非常感谢！

**Comment by chendy218** [comment]
Traceback (most recent call last):
  File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "E:\mydata\AutoXue-multiuser-master\xuexi\__init__.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by zz803abc** [comment]
> Traceback (most recent call last):
> File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 183, in _run_module_as_main
> mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 142, in _get_module_details
> return _get_module_details(pkg_main_name, error)
> File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 109, in _get_module_details **import**(pkg_name) File "E:\mydata\AutoXue-multiuser-master\xuexi__init__.py", line 13, in
> import requests
> ModuleNotFoundError: No module named 'requests'

作都的setup.cmd没写全　requests appium lxml beautifulsoup4 fuzzywuzzy都要重新安装，建议作者修改setup.cmd文件。

**Comment by zz803abc** [comment]
> > > > 之前版本有这个问题吗，我这里都能读出来全部状态，我再找找问题。
> > > 
> > > 
> > > 从昨天晚上到刚才更新的版本，都是在这一步出现问题的
> > > 我又更新了一稿，同步下来，修改配置文件用户名再试试。
> 
> 好的，非常感谢！

我这里也是同一个账号，循环三次，然后退出。我在default.ini文件已经添加了3个账号，但不知道为什么，只学第一个账号，其他的不学。第一个账号学三遍后，退出。

**Comment by XueBab** [comment]
几个版本了一直卡在 name "app" is not defined，刚才找了个朋友帮我看了看他说找不到这个app的类 是不是有一部分源码编译成二进制了？

**Comment by yangzuoming** [comment]
> 几个版本了一直卡在 name "app" is not defined，刚才找了个朋友帮我看了看他说找不到这个app的类 是不是有一部分源码编译成二进制了？

这个是退出app的错误，不是开在这里，你应该是系统卡顿，app 启动的不流畅。建议你关闭其他应用跑跑试试。
